project:
    attrs:
        description: Project for glider mission
station_id:
    attrs:
        description: Station name for water sampling
glider_trajectory:
    attrs:
        description: Glider deployment/trajectory ID
deployment_recovery:
    attrs:
        description: Water sampling taken at glider deployment or recovery
cast:
    attrs:
        description: Niskin or CTD Rosette cast number
    decimal: 0
niskin:
    attrs:
        description: Niskin bottle number
    decimal: 0
collection_method:
    attrs:
        description: Method by which the water samples were collected (e.g., Niskin, CTD Rosette, bucket)
        long_name: Collection Method
depth:
    attrs:
        long_name: Depth
        units: m
        standard_name: depth
        description: Depth at which water samples were collected
    decimal: 0
time:
    attrs:
        long_name: Time
        standard_name: time
        description: Timestamp (UTC) of the water sample collection
longitude:
    attrs:
        standard_name: longitude
        long_name: Longitude
        units: degrees_east
        description: Longitude of the water sample collection
    decimal: 6
latitude:
    attrs:
        standard_name: latitude
        long_name: Latitude 
        units: degrees_north
        description: Latitude of the water sample collection
    decimal: 6
temperature:
    attrs:
        units: degrees C
        long_name: Sea Water Temperature
        standard_name: sea_water_temperature
        description: Sea water temperature of the water sample, measured by the in-situ CTD cast or by the glider when CTD cast data were not available
    decimal: 2
salinity:
    attrs:
        units: '1'
        long_name: Sea Water Salinity
        standard_name: sea_water_practical_salinity
        description: Salinity of the water sample, measured by the in-situ CTD cast or by the glider when CTD cast data were not available
    decimal: 2
pH:
    attrs:
        units: '1'
        long_name: pH
        standard_name: sea_water_ph_reported_on_total_scale
        description: Average pH (on the Total pH scale) measured at 25°C from the water samples. These values have not been corrected for in-situ temperature, pressure or salinity.
    decimal: 4
pH_stdev:
    attrs:
        units: '1'
        long_name: pH Standard Deviation
        description: Standard deviation of pH.
    decimal: 4
TA:
    attrs:
        units: micromoles kg-1
        long_name: Total Alkalinity
        description: Average total alkalinity measured at 25°C from the water samples.
    decimal: 1
TA_stdev:
    attrs:
        units: micromoles kg-1
        long_name: TA Standard Deviation
        description: Standard deviation of total alkalinity
    decimal: 1
DIC:
    attrs:
        units: micromoles kg-1
        long_name: Dissolved Inorganic Carbon
        description: Average Dissolved Inorganic Carbon measured at 25°C from the water samples.
    decimal: 1
DIC_stdev:
    attrs:
        units: micromoles kg-1
        long_name: DIC Standard Deviation
        description: Standard deviation of DIC
    decimal: 1
pH_corrected:
    attrs:
        units: '1'
        long_name: pH
        standard_name: sea_water_ph_reported_on_total_scale
        description: Average pH (on the Total pH scale) measured from the water samples that have been corrected for in-situ temperature, pressure and salinity using the PyCO2SYS python package.
    decimal: 4
